CREATE TABLE IF NOT EXISTS category(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	description text,
	status BOOLEAN,
	createdAt date NOT NULL,
	updatedAt date NOT NULL
)

CREATE TABLE IF NOT EXISTS product(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	categoryID INTEGER REFERENCES category(id),
	name text NOT NULL CHECK (name <> ''),
	costB number NOT NULL,
	costD number NOT NULL,
	gain number NOT NULL,
	stock number NOT NULL,
	price number NOT NULL,
	status BOOLEAN,
	createdAt date NOT NULL,
	updatedAt date NOT NULL
)

CREATE TABLE IF NOT EXISTS detailInvoice(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	productID INTEGER REFERENCES product(id),
	invoiceID INTEGER REFERENCES invoice(id),
	quantity INTEGER,
	price number NOT NULL,
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS invoice(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	detailPaymentID INTEGER REFERENCES typePayment(id),
	note text,
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS detailPayment(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	invoiceID INTEGER REFERENCES invoice(id),
	typePaymentID INTEGER REFERENCES typePayment(id),
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS typePayment(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	description text,
	status BOOLEAN,
	createdAt date NOT NULL,
	updatedAt date NOT NULL
)



