CREATE TABLE IF NOT EXISTS categories(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL CHECK (name <> ''),
	description TEXT,
	status STRING,
	updatedAt TIMESTAMP,
	createdAt TIMESTAMP,
)

CREATE TABLE IF NOT EXISTS product(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	categoryID INTEGER REFERENCES categories(id),
	name text NOT NULL CHECK (name <> ''),
	costB number,
	costD number,
	gain number NOT NULL,
	stock number NOT NULL,
	price number NOT NULL,
	iva number,
	status enum,
	createdAt date NOT NULL,
	updatedAt date NOT NULL
)

CREATE TABLE IF NOT EXISTS detailInvoice(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	productID INTEGER REFERENCES product(id),
	invoiceID INTEGER REFERENCES invoice(id),
	quantity INTEGER,
	price number NOT NULL,
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS invoice(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	detailPaymentID INTEGER REFERENCES typePayment(id),
	note text,
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS detailPayment(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	invoiceID INTEGER REFERENCES invoice(id),
	typePaymentID INTEGER REFERENCES typePayment(id),
	createdAt date NOT NULL,
	updatedAt date NOT NULL,
)

CREATE TABLE IF NOT EXISTS typePayment(
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	description text,
	status BOOLEAN,
	createdAt date NOT NULL,
	updatedAt date NOT NULL
)

INSERT INTO categories(name,description,status,createdAt,updatedAt)
	VALUES('Viveres','Productos de comida',true,'2019-12-12','2019-12-12');
